version: 2
python:
  version: {{ cookiecutter.python_version }}
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .
sphinx:
  builder: html
  configuration: docs/conf.py

